// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQN1cW1XggEDSyU0weXz4g4uVZWugGZ6M',
    appId: '1:1050150379566:web:c83bf3ce79b6f64259bfbf',
    messagingSenderId: '1050150379566',
    projectId: 'biometric-voting-machine-cb2f3',
    authDomain: 'biometric-voting-machine-cb2f3.firebaseapp.com',
    databaseURL: 'https://biometric-voting-machine-cb2f3-default-rtdb.firebaseio.com',
    storageBucket: 'biometric-voting-machine-cb2f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC803MPncl2WMtK8PX1oiIlB9xDNTiPWVc',
    appId: '1:1050150379566:android:db6601471b23267059bfbf',
    messagingSenderId: '1050150379566',
    projectId: 'biometric-voting-machine-cb2f3',
    databaseURL: 'https://biometric-voting-machine-cb2f3-default-rtdb.firebaseio.com',
    storageBucket: 'biometric-voting-machine-cb2f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsuVZllPO8IpjDQDbTylWD1S3sSXpLTtI',
    appId: '1:1050150379566:ios:8a31404a9b40966959bfbf',
    messagingSenderId: '1050150379566',
    projectId: 'biometric-voting-machine-cb2f3',
    databaseURL: 'https://biometric-voting-machine-cb2f3-default-rtdb.firebaseio.com',
    storageBucket: 'biometric-voting-machine-cb2f3.firebasestorage.app',
    iosBundleId: 'com.example.biometricVotingMachine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsuVZllPO8IpjDQDbTylWD1S3sSXpLTtI',
    appId: '1:1050150379566:ios:8a31404a9b40966959bfbf',
    messagingSenderId: '1050150379566',
    projectId: 'biometric-voting-machine-cb2f3',
    databaseURL: 'https://biometric-voting-machine-cb2f3-default-rtdb.firebaseio.com',
    storageBucket: 'biometric-voting-machine-cb2f3.firebasestorage.app',
    iosBundleId: 'com.example.biometricVotingMachine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQN1cW1XggEDSyU0weXz4g4uVZWugGZ6M',
    appId: '1:1050150379566:web:1457769f471a989659bfbf',
    messagingSenderId: '1050150379566',
    projectId: 'biometric-voting-machine-cb2f3',
    authDomain: 'biometric-voting-machine-cb2f3.firebaseapp.com',
    databaseURL: 'https://biometric-voting-machine-cb2f3-default-rtdb.firebaseio.com',
    storageBucket: 'biometric-voting-machine-cb2f3.firebasestorage.app',
  );

}